
= Kế hoạch kinh doanh 2023 của VinaAS 

== Tổng quan

=== Mô hình kinh doanh

. Cung cấp giải pháp, dịch vụ tư vấn

* iBusiness: gói Chuyển đổi số Doanh nghiệp với cam kết tăng trên 10% doanh thu, 20% lợi nhuận

* iEvent: gói Chuyển đổi số sự kiện 

* iTravel: Nền tảng phát triển du lịch địa phương

* iB2B: phát triển kinh doanh, mở rộng nhà phân phối, đại lý 

. Kinh doanh mô hình iShowroom

* Qùa tặng: sticker may mắn
* iSampling: Nhũ hoàng kim, iCard, iShop, iMember, ...
* iVouchers: 


=== Chi tiết 

Kinh doanh trực tiếp:: VinaAS trực tiếp ký hợp đồng 

. Gói Chuyển đổi số iBusiness với ngân sách từ 100 triệu

* Cho thuê sản phẩm iSHOP, iShowroom theo năm
* Tư vấn Chuyển đổi số iBusiness 

* Giá gói sản phẩm 
** iBusiness for Company: 0 triệu / năm + Gói tư vấn Chuyển đổi số 3 tháng: 10 triệu 

** iDistributors: 50 triệu / năm , tặng kèm Gói tư vấn Chuyển đổi số 3 tháng: 10 triệu 

** iEnterprise: trên 100 triệu / năm , tặng kèm gói Tư vấn Chuyển đổi số 6 tháng: 20 triệu

* Gói tư vấn Chuyển đổi số:

** Gói 3 tháng: 10 triệu: 4 buổi, 15 triệu : 6 buổi
** Gói 6 tháng: 40 triệu: 20  buổi, 60 triệu : 30 buổi
** Gói 1 năm: 150-200 triệu

. Dự án Chuyển giao Hệ thống iSHOP

* Dành cho doanh nghiệp muốn triển khai iSHOP với thương hiệu riêng và bảo mật dữ liệu, tương tác với khách hàng 

* Triển khai hệ thống iSHOP: từ 200 triệu  

* Phát triển tính năng theo yêu cầu của doanh nghiệp với dự án có ngân sách từ 500 triệu 

. Vận hành Kênh TMDT kinh doanh iSHOP, iCard 

* khách hàng cá nhân mua iCard từ 149k / bộ
* shop bán hàng cần iSHOP với Gói 499k / bộ iSHOP + 1 iCard. 

Phân phối gián tiếp:: 

* Nhà phân phối sản phẩm iSHOP, iCard 

** Phân phối tới khách hàng kèm theo Sản phẩm Chính 

** Phân phối tới mạng lưới đại lý, cộng tác viên bán hàng. 

* Đối tác tư vấn Chuyển đổi số sử dụng iSHOP 

* Hiệp hội phân phối sản phẩm iSHOP, iCard 

Hợp tác giới thiệu:: 

* Giới thiệu Doanh nghiệp Chuyển đổi số: hoa hồng 10% theo dự án 


* Cộng tác viên quảng bá về sản phẩm iSHOP, iCard:

** 20-25% hoa hồng theo doanh số sản phẩm
** 5-10% cho Doanh số phát sinh trong vòng 6 tháng 

== Chuyển đổi số bằng iSHOP

iSHOP tập trung vào 3 hoạt động quan trọng của doanh nghiệp là Tìm kiếm, Phục vụ và Đánh giá khách hàng trong đó

3 Hoạt động ảnh hưởng trực tiếp tới kết quả kinh doanh là Tìm kiếm, Phục vụ và Đánh giá. *Tìm kiếm* khách hàng 



Để cải thiện Kết qủa kinh doanh, mỗi Doanh nghiệp cần tập trung vào 3 Hoạt động: Tìm kiếm, Phục vụ, Đánh giá lên 3 nhóm đối tượng: Khách hàng, Nhà phân phối, Nhân viên và Cộng tác viên. 

iSHOP cải thiện hoạt động Tìm kiếm khách hàng bằng cách

* nâng cao hiệu quả hoạt động Quảng cáo
* thúc đẩy việc giới thiệu trực tiếp tới khách hàng tiềm năng.

Thông điệp quảng cáo có tích hợp iSHOP sẽ thu hút khách hàng có nhu cầu thực hiện *tab to know* để 

