= Thư mời Hợp tác đầu tư 
:docinfo: shared
:last-update-label!:

Chào anh Tâm,

Cảm ơn anh đã quan tâm tới các sản phẩm iCard, và thiện ý đầu tư, hỗ trợ công ty em phát triển.

iCard là Công cụ tương tác số giữa nhân viên với khách hàng.
là 1 sản phẩm độc lập, thuộc bộ giải pháp QRCare, nền tảng "chuyển đổi số" Mạng lưới Doanh nghiệp Phục vụ Khách hàng và phân phối sản phẩm.

iCard đã hoàn thiện chức năng Danh thiếp số, đang bán cho cá nhân, Doanh nghiệp muốn trang bị cho nhân viên Kinh doanh, với các case study như sau:

* Cá nhân hoặc công ty nhận làm Đại lý bán hàng (chiết khấu từ 30-40%): đơn hàng đầu tiên từ 50-100 bộ iCard 
* 1 Công ty mua 20 bộ iCard cho nhân viên, sử dụng trong một sự kiện quan trọng 
* Bán cho Cá nhân (1,2 bộ iCard) để sử dụng và tặng cho khách hàng

Để có doanh thu 10.000 bộ iCard, có 3 hướng triển khai: bán cho 10k cá nhân, cho 500 Doanh nghiệp (có trên 20 nhân viên), hoặc cho 100 đại lý bán hàng (đặt hàng từ 100 bộ). Với giá 150k / bộ, cơ cấu giá thành với Doanh thu 1,5 tỷ là: 

* 50% cho Sales, marketing: 750 triệu
* 20% cho sản xuất và  server vận hành 1 năm: 300 triệu 
* 10% cải thiện sản phẩm iCard: 150 triệu
* 20% lợi nhuận: 300 triệu 

Khi hoạt động Kinh doanh vận hành ổn định và tối ưu, % lợi nhuận sẽ tăng lên, tới 30-35%.

Em đang gặp khó khăn về tìm kiếm, tuyển dụng nhân sự giỏi, trả lương ban đầu, cần thêm nguồn lực để đạt KPI 10k bộ trên trong 6-9 tháng theo các hướng bán hàng: 

* *B2C*: 1-2 Nhân viên Sales để bán trực tiếp cho Doanh nghiệp, tổ chức, cá nhân có nhu cầu

* *B2B*: 1 Nhân viên Sale để phát triển mạng lưới Đại lý bán hàng (là cá nhân hoặc doanh nghiệp)
** Cá nhân hoặc Doanh nghiệp bán iCard như tuỳ chọn, bổ sung bên cạnh sản phẩm chính
** Sinh viên, cộng tác viên bán iCard để có thu nhập 

Hiện tại em đang kiêm nhiệm việc sales, nhưng kết quả mang lại không tương xứng với Lương cho vị trí trên. Trong khi thế mạnh của em là tiếp tục phát triển các sản phẩm tiếp theo trong nền tảng QRCare bên trên.
Nếu được anh tham gia, đầu tư hỗ trợ thì quá tốt cho các việc sau, 
(em  sẽ tập trung vào cải thiện sản xuất và điều hành chung)

=== 1. Tham gia Kinh doanh iCard 

*Vai trò*:

. Xây dựng đội Sales, Marketing để đạt KPI 10k iCard trong 6-9 tháng tới. 
. Giám sát kết quả Kinh Doanh, tư vấn để cải thiện sản phẩm, bảng giá.

*Quyền lợi*: 

* Trong 2 năm đầu tiên, anh nhận 50% lợi nhuận thu được từ sản phẩm iCard. 
* Cổ phần trong mảng Kinh Doanh iCard, tách thành công ty riêng sau sau 2 năm: 
** 20% nếu đạt sau 6 tháng
** 15% nếu đạt sau 9 tháng
** 10% nếu đạt sau 12 tháng. 

*Đầu tư ban đầu*:

* Chi phí cho Đội Sales: tuyển dụng, trả lương ban đầu nếu chưa đạt doanh số
* Ký quỹ ban đầu: 150 triệu đồng. Hoàn trả 6 tháng / 1 lần, dựa trên kết quả kinh doanh. Ví dụ: tổng doanh số 6 tháng đầu là 500 triệu, 20% chi phí sản xuất là 100 triệu sẽ được hoàn trả lại,  50 triệu sẽ được hoàn trả vào tháng 12. 

*Ràng buộc*:

* Nếu hoạt động Kinh Doanh không đạt kỳ vọng sau 6 tháng, anh có thể Chuyển nhượng quyền lợi hiện tại cho Đối tác khác. Đối tác đó sẽ thanh toán các chi phí anh đã bỏ ra bao gồm cả ký quỹ.

* Nếu không phát sinh Doanh thu sau 6 tháng, hoặc không đủ Chi phí để vận hành đội Sale & Marketing, Mảng hợp tác này sẽ chuyển cho Đối tác khác, và anh nhận lại 50 triệu (1/3) số tiền ký quỹ. 

Mảng iCard có thể Kinh doanh độc lập ở thị trường Việt Nam, lợi nhuận thu được có thể tái đầu tư để mở rộng thị trường khác. Việc Gọi vốn có thể không cần thiết, hoặc cân nhắc vì những lợi ích khác. 


Việc Gọi đầu tư chủ yếu cho nền tảng QRCare, gồm iCard và các sản phẩm đang hoàn thiện như iShop, iStand, iMember...

* Nền tảng QRCare sẽ bảo đảm lợi thế cạnh tranh, khác biệt của iCard so với các đối thủ tương tự: VIPID (ở việt nam), HiHello (Mỹ).

* Khách hàng sử dụng nền tảng QRCare, nếu bao gồm iCard, sẽ mua iCard như 1 sản phẩm 1 Công ty độc lập (Thầu phụ).

=== 2. Đầu tư để Phát triển QRCare 

Có 2 lựa chọn để đầu tư vào nền tảng QRCare: 

. Đầu tư trước 15.11.2022: được quyền mua thêm tối đa 10% cổ phần (định giá theo thời điểm mua) trước 01.07.2023 

** 5% Cổ phần tương đương 150 triệu, 
** 10% Cổ phần tương đương 350 triệu,
** 15% Cổ phần tương đương 600 triệu

. Lựa chọn Chuyển đổi Cổ phần từ ICard trước 01.07.2023 (14 tháng tới) theo tỉ lệ 1/3:

** 1% cổ phần QRCare tương ứng với 3% Cổ phần iCard. 
** được quyền mua thêm tối đa 5% cổ phần trước 01.07.2023


Rất mong anh tham gia hai nội dung trên. Nếu chỗ nào cần làm rõ, hoặc thêm thông tin, góp ý thêm để hai bên trao đổi thống nhất sớm.

Trân trọng, 

P/S: Việc trình bày về nền tảng QRCare, có thể tốn thời gian, sẽ trao đổi vào các lần sau

