
== Tổng hợp công việc với

* Trung tâm Công nghệ chống hàng giả

* TrueData

* Các doanh nghiệp 


=== SỰ Kiện 

=== Giá trị khi có Menu (Bảng giá) Dịch vụ

Với doanh nghiệp có Menu::

* Dễ dàng biết được Khách hàng / không phải khách hàng sau khi giới thiệu Menu 
** khách hàng hiện tại: có nhu cầu, đủ tiền để mua, sử dụng dịch vụ
** khách hàng tương lai: có nhu cầu nhưng chưa đủ tiền 

* Dễ dàng Giới thiệu với khách hàng khi Menu: mọi nhân viên, không cần kinh nhiệm, đào tạo nhiều có thể thực hiện 

* Dễ dàng hợp tác với Doanh nghiệp khác để xây dựng Combo Dịch vụ chung

Với khách hàng:: 
* Dễ dàng ra quyết định khi có nhu cầu: 


=== Khác biệt giữa Sản xuất theo yêu cầu (Outsource) với Kinh Doanh dịch vụ 

Sản xuất theo yêu cầu::
* O bế, nhượng bộ, giảm giá để dành dự án với khách hàng
* Cắt giảm chi phí thực hiện dự án: giảm khối lượng => giảm chất lượng hoặc chèn ép nhân viên 


Kinh doanh dịch vụ::
* Chọn lọc khách hàng phù hợp: hiện tại và tương lai
* Ưu đãi hợp lý cho khách hàng 
* Sự tôn trọng của khách hàng. 

== iShop là gì? 

iShop là Giải pháp "Chuyển đổi số" Mạng lưới bán hàng để cải thiện Kết quả Kinh doanh và phục vụ khách hàng tốt hơn.

Với iShop, thông điệp truyền tải tới khách hàng được tích hợp 
"tương tác số" nhằm thúc đẩy của khách hàng tiềm năng tương tác, thực hiện những hành động tạo ra giá trị cho Doanh nghiệp. 

Liên hệ, tìm tới cửa hàng,... của khách hàng có nhu cầu; phản ánh , góp ý về dịch vụ, giới thiệu với bạn bè,... của người mua, sử dụng là những tương tác giúp cải thiện Kết quả Kinh doanh, sẽ được iShop "chuyển đổi số" vào Mạng lưới bán hàng.

iShop "số hoá" Cửa hàng, nhân viên kinh doanh và "chuyển đổi" quy trình phục vụ để thúc đẩy tương tác có giá trị từ khách hàng.

* Quảng cáo của từng Cửa hàng, ngoài thông điệp thu hút khách hàng, còn tích hợp các tương tác số cho những khách hàng có nhu cầu, thúc đẩy họ hành động: ghé vào cửa hàng để nhận ưu đãi, liên hệ với nhân viên để biết thêm về chương trình khuyến mãi,...

* Tại Cửa hàng, iShop thúc đẩy khách hàng tương tác: giới thiệu tới bạn bè người quen, hay phản ánh về chất lượng phục vụ.
Hình ảnh, thông điệp tại cửa hàng chứa iShop sẽ khuyến khích khách hàng chụp ảnh thực tế, chia sẻ trên zalo, facebook,... để giới thiệu với bạn bè, người quen. Và khi khách hàng cần hỗ trợ, phản ánh, chỉ cần thao tác chạm là liên hệ trực tiếp tới Quản lý. 



Khách hàng được khuyến khích giới thiệu sản phẩm, dịch vụ tới bạn bè, người quen

hoặc chia sẻ quảng cáo này tới bạn bè, người có nhu cầu. 




Cửa hàng, nhân viên kinh doanh được số hoá bằng iShop để