= Thư ngỏ gửi Doanh nghiệp 

:base:  font-family: Times-Roman


== thư ngỏ

Công ty Phần Mềm Tiên Tiến Việt Nam xin cảm ơn

Là Công ty Công nghệ thông tin, chuyên thiết kế giải pháp xây dựng hệ thống Công nghệ như MobileApps, Website portal cho tập đoàn, Phần mềm CRM, ERP,...

Sau hơn 10 năm hoạt động, Công ty chúng tôi đã triển khai thành công nhiều dự án cho các Doanh nghiệp đầu ngành thuộc nhiều lĩnh vực như Bảo hiểm (MAP Life), Oto (ISUZU), Sữa Nutifood, Vận Chuyển (SBS-Fedex, Gemadept), ... cho cơ quan nhà nước như Phần Mềm Thi tuyển công chức (Sở Nội vụ Daknong) Cổng thông tin ....

Qua 4 năm đầu tư phát triển, trùng hợp với chủ trương Chuyển đổi số của Chính phủ Việt Nam, vào tháng 07/2022 chúng tôi cho ra đời iShop - giải pháp Chuyển đổi số, tập trung cải thiện Kết quả kinh doanh và phục vụ khách hàng.

iShop gồm Gói sản phẩm với công nghệ đóng gói, cho phép triển khai cho Doanh nghiệp trong vòng 1-2 tuần. Sau khi Doanh nghiệp và Mạng lưới Kinh doanh được số hoá, sẽ từng bước chuyển đổi Hoạt động Bán hàng, Chăm sóc khách hàng,... để tăng tương tác và phục vụ khách hàng tốt hơn, từ đó cải thiện Kết quả kinh doanh sau vài tháng áp dụng. 

Ngoài ra, chúng tôi còn cung cấp Gói tư vấn chuyển đổi, kèm Cam kết cải thiện kết quả trên 5% khi áp dụng sản phẩm iShop. Chúng tôi đồng hành với hoạt động của Doanh nghiệp, đưa ra tư vấn chuyển đổi và đánh giá Kết quả cải thiện sau 6 tháng. Trường hợp Kết quả không cải thiện theo cam kết, chúng tôi sẽ không thu phí Gói tư vấn. 


*iStartup*: 5 triệu đồng / năm 

* Cho Doanh nghiệp không quá 3 cửa hàng, 30 nhân viên, cộng tác viên

*iCompany*: từ 20 triệu đồng / năm

* Cho Doanh nghiệp với quy mô không quá 20 cửa hàng.
* Cho Mạng lưới bán hàng không quá 20 Đại lý và 100 Cộng tác viên 

*iDistributors*: từ 50 triệu đồng / năm

* Cho Doanh nghiệp với quy mô trên 50 cửa hàng, chi nhánh
* Cho Kênh phân phối không quá 50 Nhà phân phối và 300 Cộng tác viên 

*iEnterprise*: từ 200 triệu đồng / năm

* Cho tập đoàn, doanh nghiệp lớn lớn trên 200 chi nhánh, cửa hàng

Gói tư vấn chuyển đổi số
Khi triển khai gói iCompany trở lên

Đánh giá Kết quả 3-6 tháng / lần, dựa trên tiêu chí đã thống nhất trước.

Thu phí dựa trên (Doanh thu | lợi nhuận) được cải thiện do iShop

* Kết quả tăng trên 10%, Phí tư vấn là 1.5% Kết quả (15%)
* Kết quả tăng trên 5%, Phí tư vấn là 0.5% Kết quả (10%)
* Kết quả tăng dưới 5%, không thu phí.


Giám sát, tư vấn Cách triển khai để cải thiện Kết quả

* 2 buổi / tháng với gói iCompany, iDistributors tại Doanh nghiệp
* 4 buổi / tháng với Gói iEnterprise tại Doanh nghiệp

== Sơn Zebra 

=== Tổng hợp 
* Doanh thu 60 tỷ / năm : 30% nhà sản xuất, 70% phân phối
* Ngân sách marketing: 1.7%-3% Doanh thu: 1 tỷ - 1,8 tỷ / năm
* 45 nhà phân phối ~ 200 triệu / năm 
* cửa hàng tân phú: 10 tỷ / năm 
* mục tiêu 2025: 600 tỷ / năm 

* Thị trường miền Nam

** Khai thác đại lý đang có
** Bán lẻ tới thầu thi công / chủ đầu tư 



=== Plan: Digital marketing : 2023 30% ~ 300 triệu / năm 
* Bộ iShop: 50 triệu / năm ~ 25%
** công ty: 10 ishop + 50 icard
** Nhà phân phối: 40 ishop / 45 Nhà phân phối 
** Thầu xây dựng / khách sỉ / lẻ: 200 icard 

* Digital marketing: 100 triệu / năm 

** Content : 20 triệu
** Ads: Facebook / zalo : 50 triệu 
** SEO: 30 triệu 

* POSM / Sales bán hàng : 150 triệu 


=== Gói tư vấn 6 tháng:
- doanh thu tăng 10% = 6 tỷ: 1,8 tỷ tăng => 180 triệu / năm


== Thư ngỏ gửi Doanh nghiệp 

Kính gửi anh / chị .... Công ty 

[cols="1,^3"]
|===
| công ty phần mềm tiên tiến việt nam

|There isn't a horizontal alignment operator on this column's specifier, so the column falls back to the default horizontal alignment.
Content is left-aligned by default.
|===

Em là Quốc Bảo, Công ty Phần Mềm Tiên Tiến Việt Nam.

Xin giới thiệu iShop, giải pháp *cải thiện Kết quả Kinh doanh* bằng cách Chuyển đổi số Nhân viên, Cửa hàng kinh doanh, Kênh Phân phối của Quý công ty. Doanh thu của Quý công ty có thể tăng trên 10% sau vài tháng triển khai iShop. 



Giải pháp iShop gồm *Gói công cụ* và *Gói tư vấn chuyển đổi* 

Gói Công cụ gồm nhiều bộ iShop, iCard (xem slide đính kèm) trong đó:

** iShop dành cho Cửa hàng, đội ngũ kinh doanh, Nhà phân phối, Đại lý bán hàng
** iCard dành cho nhân viên, cộng tác viên bán hàng

có mức giá khác nhau dựa trên quy mô, nhu cầu triển khai của Doanh nghiệp như sau: 

. Gói iStartup: 5.000.000 / năm, bộ iShop, iCards triển khai 

** Cho Công ty vừa và nhỏ, có dưới 20 nhân viên, cộng tác viên Kinh doanh và có dưới 3 Cửa hàng Kinh doanh

** gồm 5 bộ iShop, 20 bộ iCard đi kèm 1 buổi tư vấn trực tiếp và 10 giờ hướng dẫn online 

. Gói iCompany: từ 20 triệu đ/ năm

** cho Doanh nghiệp có nhiều hơn 10 cửa hàng, hoặc Mạng lưới kinh doanh với trên 20 Nhà phân phối, Đại lý và không quá 100 Nhân viên, Cộng tác viên kinh doanh. 

** gồm 20 bộ iShop, 100 bộ iCard đi kèm 3 buổi tư vấn trực tiếp và 30 giờ hướng dẫn Online 

. Gói iEnterprise: 100 triệu đ/ năm 
** cho Doanh nghiệp có nhiều hơn 50 cửa hàng hoặc Mạng lưới Kinh Doanh với trên 100 Nhà Phân phối/ Đại lý bán hàng
** Gồm 100 bộ iShop, 400 bộ iCard còn 10 buổi tư vấn, hướng dẫn trực tiếp hoặc 50 giờ hướng dẫn Online

Sau vài tuần tuần triển khai, Mạng lưới Kinh doanh của Quý công ty sẽ được số hoá và dần dần chuyển đổi. Quý công ty có thể thí điểm cho quy mô nhỏ bằng gói iStartup, và khi Kết quả được kiểm chứng, có thể nâng cấp lên Gói cao hơn. 

Ngoài ra, Quý công ty triển khai thêm thêm các Công cụ khác hoặc yêu cầu chúng tôi phát triển các hệ thống riêng như MobileApp, CRM, ERP,... 

Với các gói iCompany, iEnterprise, chúng tôi cung cấp thêm Gói tư vấn chuyển đổi để đồng hành với Quý công ty trong 6-12 tháng đầu. 
Dựa trên tiêu chí thống nhất, nếu Kết quả Kinh doanh được cải thiện trên 5%, chúng tôi mới thu phí Gói tư vấn, chiếm từ 5-15% của phần tăng thêm. 


Chúng tôi sẵn sàng gửi 1 bộ iShop, iCard để thí điểm miễn phí trong 1 tuần. 
Nếu anh / chị quan tâm, vui lòng phản hồi để chúng tôi tư vấn và gửi sản phẩm mẫu.

Cảm ơn rất nhiều.

////

=== Cách gửi thư

Ưu điểm format pdf:
** trang trọng, lịch sự 

Nhược điểm: 
** khó đọc trên điện thoại , gửi email 


Email:

. tiêu đề, giới thiệu cơ bản, kèm hình click vào xem chi tiết 
. ishop chứa nội dung thư ngỏ, link pdf, slide giải pháp 

Thư ngỏ gửi zalo, share 

. hình thư ngỏ chứa qrcode ishop 

Thư ngỏ bằng giấy
- thư giới thiệu 
- gửi bưu điện tới doanh nghiệp







