== Nhu cầu Khách đoàn cần Gói phục vụ

* Đang có một số nhu cầu Khách đoàn (dưới 10 người) mà các đơn vị 
Tour có thể khai thác.

=== Khách đoàn gia đình: 

có nhu cầu chăm sóc sức khoẻ (nha khoa, làm đẹp, khám bệnh,…) kết hợp với thăm gia đình, và du lịch trong ngày. ví dụ: 

. Ba mẹ vô sài gòn thăm con cái dài ngày (trên 2 tuần), sẽ có nhiều thời gian rảnh để chăm sóc nha khoa, khám bệnh, và đi chơi, giải trí trong thời gian con cái đi làm. Có vài điểm lợi như:

* Giảm thời gian nghỉ làm của con cái để đưa đón, chăm lo cho cha mẹ,
* Chất lượng chăm sóc sức khoẻ ở Hcm cao, đáng tiền với miền trung.
* Các gói giải trí chất lượng, phù hợp với bậc lớn tuổi.

. Tour gia đình từ Campuchia: tham dự lễ hội, sự kiện giải trí ở việt nam, kết hợp với chăm sóc nha khoa, sức khoẻ hoặc làm đẹp.
* Chất lượng nha khoa, làm đẹp ở việt nam cao hơn
* phát triển khách đoàn, giới thiệu nhiều dịch vụ du lịch, sản phẩm đặc trưng ở việt nam

. Tour gia đình việt kiều từ Mỹ, Úc,…

=== Khách đoàn của Doanh nghiệp: công tác vài ngày tại các địa phương trong và ngoài nước.

1. Công ty đánh giá, cấp chứng chỉ ISO: BSI, BV, SGS, TVC, Q,….

Các công ty này có đội ngũ xếp lịch cho đoàn công tác (Auditors) tới các nhà máy trên các địa phương đánh giá chất lượng (trong vài ngày) trước khi cấp chứng chỉ. 

Nhu cầu::
	
** Phục vụ công tác: Xe đưa đón riêng cho nhóm nhỏ, hoặc từng Auditor, sắp xếp chỗ ăn uống, khách sạn, … trong quá trình công tác vài ngày, vài tuần. Chi phí này thường là khách hàng của các công ty này chi trả, hoặc tính vào gói Chứng nhận, được tính theo số lượng auditor x số ngày đánh giá, (đơn giá trên 5 triệu đồng Auditor / ngày)
	
** Tổ chức sự kiện: các doanh nghiệp này thường xuyên tổ chức hội thảo, sự kiện đào tạo, mời khách hàng (nhân viên của doanh nghiệp cần đánh ISO) tới để giới thiệu trên khắp cả nước.
Hiện tại 

Hiện trạng:: 
** các doanh nghiệp này cấp Thẻ taxi riêng cho Auditor, và có nhân viên để đặt phòng, sắp xếp chỗ ăn ở cho vài chục vài trăm khách đoàn hàng tháng.

** Auditor có thể tự đặt phòng, lấy hoá đơn trả cty sau.

Đề xuất:: 

** Đơn vị Tour đảm nhận 1 phần vai trò này, đã giảm khối lượng và nhân sự (xếp lịch, lên chi phí,…) cho doanh nghiệp trên, tăng chất lượng phục vụ mà với chi phí ko đổi.

** Đơn vị Tour sẽ ký hợp đồng dài hạn,hàng năm, với doanh số phục vụ tầm vài trăm triệu, vài tỉ / tháng tuỳ quy mô doanh nghiệp. 
Tuỳ doanh số đạt được, trích % hoa hồng (và quà tặng) cho Doanh nghiệp, hoặc các trừ Chi phi cho các nhu cầu khác, liên quan tới tổ chức sự kiện. 

** Đơn vị tour phối hợp với iShowroom để phục vụ các Công ty này và cả khách hàng của họ. 

== Vai trò của iShowroom 

Với khách đoàn gia đình::

- Giới thiệu các gia đình có nhu cầu về Gói phục vụ trên.

- Hợp tác với các Hội đồng hương các địa phương, đồng tổ chức các lễ hội, tour du lịch, ... hướng tới khách đoàn.

- Tiếp nhận phản hồi của các gia đình, 

Với các doanh nghiệp cấp ISO này::

- Đối tác Giới thiệu: các giải pháp, lơi ích của ISO tới các doanh nghiệp có nhu cầu, nhà máy, tập đoàn,...

- Cung cấp Gói hỗ trợ  tổ chức sự kiện : giới thiệu tới khách hàng mới, cung cấp gói địa điểm, đi lại,.. với chi phí tối ưu và phù hợp.

- Cung cấp các Gói phục vụ Công tác đoàn, hợp tác với đơn vị Tour (thầu phụ) đảm nhận thực hiện, iShowroom sẽ giám sát chất lượng. 

== Vai trò của đơn vị Tour

- Cung cấp các Gói dịch vụ phù hợp, mở rộng mạng lưới điểm lưu trú, khách sạn, nhà hàng phù hợp với khách đoàn trên. 

- Phối hợp với iShowroom cùng tiếp cận khách hàng.




